language: node_js
node_js:
  - "10"
cache: npm
addons:
  ssh_known_hosts: wolfblade.info
before_install:
- openssl aes-256-cbc -K $encrypted_9ccf222664ed_key -iv $encrypted_9ccf222664ed_iv
  -in wolfblade_id_rsa.enc -out /tmp/wolfblade_id_rsa -d
node_js:
- node
before_script:
- npm install -g gulp-cli gulp
script:
- gulp
env:
  global:
    secure: npLe0JLiNEjrckd6loFgYCZJDL5EP++A9+2Ch7IzfxVEiHwekk6ljtHupNAl4473ULXoXlLzfghkVN0xJ+bXwDIErLYBbXIXwN460/VgGkU+pQn3QFTcYWSqpZeGMvSMYZb2ixwYever332oZuZ1uKrcaN/ZLwzc9p+wQ+Z6GiapPx7ksktnofJ355ggcC5e5zPEYXbQrfW5WyKxB3xUeaVKzSlzVMBG528IMSR/KJVZA4g9x9Tt8bRzO8AY+puFRtXlbDPGVo2/Ieq1a3JBLedLorJyE1qhkdr9DPe5xlbQob0G6iZ2VgBlKE64hq72VbCPXn+Rn7T90nzzi6rpO0/VkHOmgmyA1y7lhINGirNVoEzdia/FHrw9VA3w+NLvJkhvwHjnHRcovPNM+TNZ0A6gHzCq0TU6JBSrTNkuJu6+ZuXD4/AHSJ4DGpuRxzNHX1mTo/KEK/cOVFhKMlAUzUSGVm4T1n2wI+gcXdWY1UDBY3Iafavdq8Xa+xyLH5qVBRRklJtRvHkIFaghjnVPMh0VNdC9J2ZTwpU0EvgP4AFcmCGZIHQ56oOIaGyKvU5Tg6jUKCDrxN9/Rkihn3/5JvQYq4V7IA2QGazJX43d6fv/4HElzsThxTJgKrLLMgJBITN/IYnOTKnqLY+VOj6Yqn2fmNRpXHE+JQ3lv5x8/g0=
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/wolfblade_id_rsa
- ssh-add /tmp/wolfblade_id_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet dist/ wolfblade@wolfblade.info:~/public
  on:
    all_branches: true
